<a href="https://colab.research.google.com/github/marisukanis/gitfirstproject/blob/pythonproject1/numpy_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
#2x3 matrix (2 rows and 3 columns)
B = np.array ([[3,7,4], [9,3,5]])
B

array([[3, 7, 4],
       [9, 3, 5]])

In [ ]:
B.shape


(2, 3)

In [ ]:
#Matrix creation using np. arange()
C = np.arange(2,8,0.5)
C

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

In [ ]:
#using np.linspace(start, end, count) - (0,1,5) - 5 numbers from 0 to 1 at equal distances
D = np.linspace(2,8,100)
D

In [12]:
matrix1 = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
matrix2 = np.array([[3, 2, 3], [4, 3, 1], [7, 3, 1]])
print(matrix1, '\n', '\n', matrix2)
print(matrix1.shape)

[[1 4 7]
 [2 5 8]
 [3 6 9]] 
 
 [[3 2 3]
 [4 3 1]
 [7 3 1]]
(3, 3)


In [14]:
matrix1.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])