<a href="https://colab.research.google.com/github/marisukanis/gitfirstproject/blob/pythonproject1/statistics_and_proability_task_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Task 1



Create a numpy array with values ​​from 1 to 9, display and then invert this array (first element becomes last, etc.).

In [ ]:
import numpy as np

a = np.arange(1, 10)
print(a)
print(a[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


### Task 2

Create the following numpy array: [1, 23, 4, 31, 1, 1, 4, 23, 4, 1]; and then list all the unique (non-repeating) elements.

In [ ]:
import numpy as np

a = np.array([1, 23, 4, 31, 1, 1, 4, 23, 4, 1])
print(a)
print(np.unique(a))

[ 1 23  4 31  1  1  4 23  4  1]
[ 1  4 23 31]


### Task 3

Create a 3x3 matrix (using reshape) with values ​​between 2 and 10.

In [ ]:
import numpy as np

a = np.arange(2, 11).reshape(3, 3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Task 4


Create an array with six random values ​​between 10 and 30.

In [ ]:
import numpy as np

a = np.random.randint(low=10, high=30, size=6)
print(a)

[10 10 13 22 17 28]


### Task 5

From the array of values: [23, 45, 112, 150, 43, 254, 95, 8] filter those that are greater than 100.

In [ ]:
import numpy as np

a = np.array([23, 45, 112, 150, 43, 254, 95, 8])
print(a)
print(a[a > 100])
print(a[np.where(a > 100)])

[ 23  45 112 150  43 254  95   8]
[112 150 254]
[112 150 254]


### Task 6

Create the following 4x4 matrix, then:
* display an item from the second row and third column,
* calculate its determinant,
* calculate its trace (sum of elements on the main diagonal),
* find the largest and smallest element.

$ \begin{bmatrix}
1 & 15 & 4 & 13 \\
8 & 21 & 3 & 12 \\
11 & 13 & 11 & 5 \\
32 & 13 & 0 & 2 
\end{bmatrix}  $

In [ ]:
import numpy as np

a = np.array([[1, 15, 4, 13], [8, 21, 3, 12], [11, 13, 11, 5], [32, 13, 0, 2]])
print(a[1][2])
print(np.linalg.det(a))
print(a.diagonal().sum())
print(a.min(), a.max())

3
-19963.99999999999
35
0 32


### Task 7



Create any array of values ​​and then calculate the mean and median.

In [ ]:
import numpy as np

a = np.array([5, 4, 3, 5, 3.5, 2, 1.34, 8])
print(a)
print(np.mean(a))
print(np.median(a))

[5.   4.   3.   5.   3.5  2.   1.34 8.  ]
3.98
3.75


### Task 8

Create any array of values ​​and then normalize them - i.e. subtract the mean from each element of the array and divide by the standard deviation.

In [ ]:
import numpy as np

a = np.array([5, 4, 3, 5, 3.5, 2, 1.34, 8])
print(a)
b = (a - np.mean(a)) / np.std(a)
print(b)

[5.   4.   3.   5.   3.5  2.   1.34 8.  ]
[ 0.52391807  0.0102729  -0.50337227  0.52391807 -0.24654968 -1.01701743
 -1.35602324  2.06485358]


### Task 9

Create a function that takes two vectors (both of the same dimension) as a numpy array and returns the Euclidean distance between them.

 $ d\left( p,q\right)   = \sqrt {\sum _{i=1}^{n}  \left( q_{i}-p_{i}\right)^2 } $

In [ ]:
def distance1(v1, v2):
    return np.sqrt(np.sum((v1 - v2) ** 2))


def distance2(v1, v2):
    return np.linalg.norm(v1 - v2)


a = np.array([1, 0, 1, 2, 3])
b = np.array([1, 2, -1, 0, 0])
print(distance1(a, b))
print(distance2(a, b))

4.58257569495584
4.58257569495584


### Task 10

Using the Shapiro-Wilk test, check whether the given sample has a normal distribution: [0.873, 2.817, 0.121, -0.945, -0.055, -1.436, 0.360, -1.478, -1.637, -1.869]


In [ ]:
from scipy.stats import shapiro

data = np.array([0.873, 2.817, 0.121, -0.945, -0.055, -1.436, 0.360, -1.478, -1.637, -1.869])
stat, p = shapiro(data)
print(stat, p)

if p > 0.05:
	  print("Rozkład normalny")
else:
	  print("Rozkład oddalony od krzywej Gaussa")

0.8951009511947632 0.19340917468070984
Rozkład normalny
